### PR TITLE
Fix/130 selialization plugin

### LINKED ISSUE #130: BUG: Kotlin serialization plugin not activated.
The plugin was removed from the build gradle in PR #120 

This causes networpk responses to be unparseable

### PR DESCRIPTION
**Pull request by ninovanhooff**
## Why is this important?
parsing network responses is broken. 

## Notes
- The serializationplugin was removed from the build gradle in PR https://github.com/Q42/Template.Android/pull/120
- The cause of the problem was unclear because no error logging was in place for this, so added that as well

fixes #130

### CODE REVIEW

File: data/main/src/main/kotlin/nl/q42/template/data/main/UserRepositoryImpl.kt [hunk 1]
```diff
@@ -22,13 +22,19 @@ internal class UserRepositoryImpl @Inject constructor(
...
         // store locally
-        userEntityActionResult.getDataOrNull()?.let { userEntity ->
-            userLocalDataSource.setUser(userEntity)
-        }
+        when (userEntityActionResult) {
+            is ActionResult.Success -> {
+                userLocalDataSource.setUser(userEntityActionResult.data)
+            }
 
+            is ActionResult.Error -> {
```
Comment (ninovanhooff) [inline data/main/src/main/kotlin/nl/q42/template/data/main/UserRepositoryImpl.kt]: We can move this error handler one level deeper, to the RemoteDataSource. Handling errors deeper /earlieris better, so we should probably do that, right?

Comment (Frank1234) [reply data/main/src/main/kotlin/nl/q42/template/data/main/UserRepositoryImpl.kt]: the success needs to be done here, the logging can indeed go down.

**Review by Frank1234 — APPROVED** [review]
